import { useState } from 'react';
import { useResource } from './data';
import { count, day, fixed, gamesUrl, pct } from './sensoryData';
import type { GameDetail, GamesPage, Probe, Summary } from './sensoryTypes';

function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div className="state compact" role="alert"><h2>Evidence unavailable</h2><p>{message}</p><button onClick={retry}>Try again</button></div>; }
function ProbeCard({ probe, role }: { probe: Probe; role: string }) {
  return <article className="probe-card"><span className="eyebrow">{role} opportunity</span><h2>{probe.team}</h2><div className="quality-score"><strong>{fixed(probe.quality, 3)}</strong><span>Encoded quality<br/>0–1 training reference scale</span></div><div className="quality-track" aria-hidden="true"><span className="quality-range" style={{ left: `${probe.interval[0]*100}%`, width: `${(probe.interval[1]-probe.interval[0])*100}%` }}/><i style={{ left: `${probe.quality*100}%` }}/></div><p className="fine-print">95% encoder parameter interval: {fixed(probe.interval[0], 3)}–{fixed(probe.interval[1], 3)}. Quality is not a win probability.</p><dl className="probe-stats"><div><dt>Stimulus</dt><dd>{probe.condition}</dd></div><div><dt>Recruited sensory cells</dt><dd>{probe.recruited_ids.length}</dd></div><div><dt>Requested rate / contacted cell</dt><dd>{fixed(probe.requested_hz, 1)} Hz</dd></div></dl><details><summary>Recruited body IDs and source rate</summary><p className="body-ids">{probe.recruited_ids.length ? probe.recruited_ids.join(', ') : 'No cells contacted in this probe.'}</p><p>Source anchor: {probe.source_measurement.mM} mM {probe.source_measurement.tastant}, {probe.source_measurement.mean_hz} ± {probe.source_measurement.sem_hz} Hz (mean ± SEM), first second. Applied as a homogeneous generator request.</p><p>{probe.source_measurement.sensillum}.</p></details></article>;
}
function Matchup({ gameId }: { gameId: string }) {
  const resource = useResource<GameDetail>('/api/sensory/games/' + encodeURIComponent(gameId));
  if (resource.error) return <><a className="text-link" href="#backtest">← All confirmation games</a><ErrorState message={resource.error} retry={() => void resource.reload()}/></>;
  if (!resource.data) return <p className="state" role="status">Loading matchup evidence…</p>;
  const d = resource.data, g = d.game;
  const winner = g.home_win ? g.home : g.away, pick = g.neural >= .5 ? g.home : g.away;
  return <><a className="text-link" href="#backtest">← Back to game results</a><section className="matchup-heading"><span className="eyebrow">{day(g.start_time)} · {g.start_time.slice(11,16)} UTC · MLB confirmation</span><h1>{g.away}<span className="at">at</span>{g.home}</h1><div className="matchup-verdict"><span className={g.correct ? 'tag success' : 'tag miss'}>{g.correct ? 'Correct pick' : 'Incorrect pick'}</span><p>Pipeline pick: <strong>{pick}</strong> · Actual winner: <strong>{winner}</strong></p></div></section><section className="probability-card"><div><span>Away win · {g.away}</span><strong>{pct(1-g.neural)}</strong></div><div><span>Home win · {g.home}</span><strong>{pct(g.neural)}</strong></div><div className="probability-track" aria-label={`Home win probability ${pct(g.neural)}`}><span style={{ width: `${(1-g.neural)*100}%` }}/></div><p className="fine-print">Frozen external readout · Encoder-only home probability {pct(g.encoder_only)} · Same-information home probability {pct(g.same_information)}</p></section><section className="probe-grid"><ProbeCard probe={d.away} role="Away"/><ProbeCard probe={d.home} role="Home"/></section>
    <section className="response-section"><div className="section-intro"><span className="eyebrow">Recorded simulation measurements</span><h2>What the gustatory outputs did.</h2><p>{d.trace_note}</p><p>Stimulus: {d.stimulus_window_ms[0]}–{d.stimulus_window_ms[1]} ms within a {d.duration_ms} ms probe. Every exposure starts from reset.</p><p className="fine-print">{d.achieved_input_note}</p></div><div className="output-chart"><div className="chart-key"><span><i className="swatch away"/>Away</span><span><i className="swatch home"/>Home</span><span>Simulated output rate (Hz)</span></div>{d.output_cells.map((cell, i) => { const max = Math.max(...d.away.outputs_hz, ...d.home.outputs_hz, 1); return <div className="output-row" key={cell.body_id}><strong>{cell.native_alias.replace('Shiu 2022: ', '')} <small>{cell.type} · {cell.body_id}</small></strong>{(['away','home'] as const).map(side => <div className="bar-line" key={side}><span className={`response-bar ${side}`} style={{ width: `${d[side].outputs_hz[i]/max*75}%` }}/><span>{fixed(d[side].outputs_hz[i], 2)} Hz</span></div>)}</div>; })}<details><summary>Individual recorded seeds</summary><div className="table-wrap"><table><thead><tr><th>Opportunity / seed</th>{d.output_cells.map(cell => <th key={cell.body_id}>Body {cell.body_id}</th>)}</tr></thead><tbody>{(['away','home'] as const).flatMap(side => d[side].seeds.map((seed, i) => <tr key={`${side}-${seed}`}><th>{side} / {seed}</th>{d[side].outputs_by_seed[i].map((value, index) => <td key={index}>{fixed(value, 1)} Hz</td>)}</tr>))}</tbody></table></div></details></div></section><aside className="scope-note"><strong>Two independent probes, compared externally</strong><p>Both teams can receive attractive inputs. These are saved circuit responses to contact patterns; the fly does not see team names or make an in-circuit sports choice.</p></aside></>;
}
function Results({ url, offset, setOffset }: { url: string; offset: number; setOffset: (offset: number) => void }) {
  const resource = useResource<GamesPage>(url);
  if (resource.error) return <ErrorState message={resource.error} retry={() => void resource.reload()}/>;
  if (!resource.data) return <p className="state compact" role="status">Loading game results…</p>;
  const d = resource.data;
  return <><div className="filtered-summary" role="status"><strong>{count(d.total)} matching games</strong><span>Filtered accuracy: <b>{pct(d.summary.accuracy)}</b></span><span>Filtered log loss: <b>{fixed(d.summary.log_loss)}</b></span></div><p className="fine-print">Subset summaries are descriptive. The full confirmation result and its confidence interval are unchanged.</p>{!d.total ? <div className="state compact"><h2>No games match these filters.</h2><p>Choose another team or date range, or clear the filters.</p></div> : <><div className="table-wrap games-table" role="region" aria-label="Confirmation games; scroll horizontally for all columns" tabIndex={0}><table><caption>Historical probabilities recorded before comparison with outcomes · dates in UTC</caption><thead><tr><th>Date</th><th>Matchup / actual winner</th><th>Home win probability</th><th>Pick result</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{d.games.map(g => <tr key={g.game_id}><td>{day(g.start_time)}</td><th scope="row"><a href={'#backtest/' + encodeURIComponent(g.game_id)}>{g.away} <span className="muted">at</span> {g.home}</a><small>Won: {g.home_win ? g.home : g.away}</small></th><td><span className="probability-number">{pct(g.neural)}</span><span className="mini-probability" aria-hidden="true"><i style={{ width: `${g.neural*100}%` }}/></span></td><td><span className={g.correct ? 'outcome correct' : 'outcome incorrect'}>{g.correct ? 'Correct' : 'Incorrect'}</span></td><td><a className="row-arrow" aria-label={`Inspect ${g.away} at ${g.home} on ${day(g.start_time)}`} href={'#backtest/' + encodeURIComponent(g.game_id)}>↗</a></td></tr>)}</tbody></table></div><div className="pagination"><span>Showing {count(offset+1)}–{count(Math.min(offset+d.limit, d.total))} of {count(d.total)}</span><div><button disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset-d.limit))}>← Previous</button><button disabled={offset+d.limit >= d.total} onClick={() => setOffset(offset+d.limit)}>Next →</button></div></div></>}</>;
}
export default function Backtest({ data, gameId }: { data: Summary; gameId: string }) {
  const [team, setTeam] = useState(''), [start, setStart] = useState(''), [end, setEnd] = useState(''), [offset, setOffset] = useState(0);
  const change = (setter: (v: string) => void, value: string) => { setter(value); setOffset(0); };
  const url = gamesUrl(team, start, end, offset);
  if (gameId) return <Matchup key={gameId} gameId={gameId}/>;
  return <><section className="page-heading explorer-heading"><div><span className="eyebrow">The complete 2023 confirmation</span><h1>Every game.<br/>Every recorded probability.</h1><p className="lede">Explore the {count(data.evaluation.metrics.neural.n)} eligible MLB matchups, including every correct and incorrect pick.</p></div><a className="button" href="/api/sensory/downloads/predictions" download>Download all games ↓</a></section><div className="full-result-note">Full confirmation: <strong>{pct(data.evaluation.metrics.neural.accuracy)}</strong> accuracy · <strong>{data.evaluation.accuracy_interval.map(x => pct(x)).join('–')}</strong> 95% interval</div><form className="filters" onSubmit={e => e.preventDefault()}><label>Team<select aria-label="Team" value={team} onChange={e => change(setTeam, e.target.value)}><option value="">All teams</option>{data.teams.map(t => <option key={t}>{t}</option>)}</select></label><label>From (UTC)<input type="date" value={start} onChange={e => change(setStart,e.target.value)}/></label><label>Through (UTC)<input type="date" value={end} onChange={e => change(setEnd,e.target.value)}/></label><button type="button" className="clear-button" onClick={() => { setTeam(''); setStart(''); setEnd(''); setOffset(0); }}>Clear filters</button></form>{start && end && start > end ? <p className="state compact" role="alert">Start date must be on or before end date.</p> : <Results key={url} url={url} offset={offset} setOffset={setOffset}/>}</>;
}
