import { count, fixed, methodNames, pct } from './sensoryData';
import type { Summary } from './sensoryTypes';
export function Pipeline() {
  return <ol className="pipeline">{[
    ['Pregame information', 'Earlier Elo, form, win rate, score margin and rest. Results enter with a 48-hour delay, in UTC-day batches.'],
    ['Independent qualities', 'A training-fitted encoder scores each team against a fixed reference and preserves parameter uncertainty. Both teams can be attractive.'],
    ['Sweet / bitter probes', 'Quality selects contacted sweet cells. Only a quality interval wholly below 0.2 selects the bitter probe. Each exposure starts from reset.'],
    ['Gustatory responses', 'The frozen MaleCNS circuit produces four measured Clavicle and Quasimodo outputs. Identical probes reuse recorded responses.'],
    ['External probability', 'Log-transformed response differences enter a readout fitted on training games. This comparison is performed outside the circuit.'],
  ].map(([title, body], index) => <li key={title}><span className="step-number">0{index+1}</span><h3>{title}</h3><p>{body}</p></li>)}</ol>;
}
export default function SensoryMethods({ data }: { data: Summary }) {
  return <><section className="page-heading"><span className="eyebrow">Pipeline & methods</span><h1>Follow the signal.<br/>Keep the limits in view.</h1><p className="lede">A biological wiring diagram supplies the circuit. The sports translation and probability readout are engineered and fitted externally.</p></section><Pipeline/>
    <section className="methods-grid"><article><span className="eyebrow">01 / Chronological separation</span><h2>Fit, select, then confirm.</h2><ol className="timeline">{(['training', 'development', 'confirmation'] as const).map(split => <li key={split}><span>{split}</span><strong>{data.splits[split].years}</strong><p>{count(data.splits[split].n)} eligible games</p></li>)}</ol><p>The candidate was frozen before retrieving 2023 confirmation data. Confirmation changed no fitted parameters and required no new neural calls. The 2023 period is now used evidence.</p><p>Resumed or suspended games were excluded ({data.evaluation.exclusions.resumed_or_suspended}), along with unplayed games ({data.evaluation.exclusions.unplayed}). Retrospective schedule corrections and unknown historical publication times limit interpretation.</p></article>
    <article><span className="eyebrow">02 / What stimulation means</span><h2>Contact patterns, not food doses.</h2><p>The encoder recruits a nested set of source-proposed sweet sensory cells, or a bitter population when the full quality interval is low. Home and away use the same mapping, with a fitted home-field term. There is no pairwise normalization that forces a loser to be bad.</p><p>First-second sucrose and caffeine measurements inform requested firing rates. Transferring those rates uniformly across proposed cell populations and varying contact extent are engineering assumptions, not measured dose laws. The precontact baseline is modeled as zero.</p><p>All probes run with plasticity off. This is a conditional second-order gustatory response; it does not qualify feeding, biological aversion or an innate choice.</p></article></section>
    <section className="methods-grid"><article><span className="eyebrow">03 / Readout populations</span><h2>Four measured outputs.</h2><div className="cell-list">{data.output_cells.map(cell => <div key={cell.body_id}><strong>{cell.native_alias.replace('Shiu 2022: ', '')}</strong><span>{cell.type} · Body {cell.body_id}</span></div>)}</div><p>Each output is a simulated firing rate during the one-second stimulus, averaged over three common seeds. Matchup details show a lookup of these frozen measurements, not a new simulation or a live brain animation.</p></article>
    <article><span className="eyebrow">04 / Uncertainty</span><h2>Compare paired games.</h2><p>The confirmation interval resamples complete ISO weeks: {count(data.evaluation.replicates)} resamples across {data.evaluation.weeks} observed blocks. Within-season dependence and the choice of block length remain limitations.</p><p>Below, positive improvement means the complete pipeline has lower log loss. A range spanning zero does not establish added benefit.</p><div className="table-wrap"><table><thead><tr><th>Comparator</th><th>Loss improvement</th><th>95% interval</th></tr></thead><tbody>{(['uniform','prior','encoder_only','same_information'] as const).map(key => { const pair = data.evaluation.paired_loss[key]; return <tr key={key}><th scope="row">{methodNames[key]}</th><td>{fixed(-pair.mean)}</td><td>{fixed(-pair.interval[1])} to {fixed(-pair.interval[0])}</td></tr>; })}</tbody></table></div><p className="fine-print">Full-pipeline accuracy interval: {data.evaluation.accuracy_interval.map(x => pct(x)).join('–')}. This interval does not apply to filtered game subsets.</p></article></section>
    <section className="downloads"><div><span className="eyebrow">Evidence desk</span><h2>Inspect the original artifacts.</h2><p>Every download contains the validated frozen bytes.</p><details className="provenance"><summary>Identity, source and hashes</summary><dl><dt>Confirmation</dt><dd>{data.identity}</dd><dt>Frozen candidate</dt><dd>{data.candidate}</dd><dt>Source</dt><dd><a href={data.source.source_url}>MLB Stats API · 2023 regular-season schedule</a></dd><dt>Retrieved</dt><dd>{data.source.source_fetched_at}</dd></dl>{data.downloads.map(file => <p key={file.id}><strong>{file.label}</strong><br/><code>{file.sha256}</code></p>)}</details></div><ul>{data.downloads.map(file => <li key={file.id}><a href={file.url} download><span>{file.label}</span><span aria-hidden="true">↓</span></a></li>)}</ul></section>
    <aside className="scope-note"><strong>A historical result, with a specific claim</strong><p>Better-than-chance performance belongs to the complete fitted pipeline. Incremental neural value, neural learning, in-circuit choice, feeding behavior, prospective performance and betting profit remain unestablished.</p></aside>
  </>;
}
